<font size="5">**Production scheduling**</font>

A set of $n$ products must be processed on $m$ machines. 
The estimated processing time (in hours) for the $i$-th products on the $k$-th machine is given by $p_{ik}$, with $i \in I=\{1,\ldots,n\}$ and $k \in K=\{1,\ldots,m\}$.
For each product $i \in I$ we have a deadline $d_i$.
Each machine cannot process more than one product at the same time.
For simplicity, we assume that each product has to be processed on the machines in the order induced by the indices of the machines, i.e., first on machine 1, then on machine 2, and so on.

Consider the following data:

$n=6$, $m=3$, $d = (38,40,35,35,37,20)$

| $p_{ik}$ | 1 | 2 | 3 | 4 | 5 | 6 |
| --- | --- | --- | --- | --- | --- |--- |
| 1 | 3 | 4 | 2 | 7 | 8 | 3 |
| 2 | 6 | 8 | 4 | 9 | 3 | 4 |
| 3 | 4 | 1 | 5 | 6 | 7 | 4 |

As an example, product 6 must be processed for 3 hours by machine 1, then must be processed for 4 hours by machine 2, and 4 hours by machine 3.



**1)** <font size="4"> Give a mixed-integer linear formulation for the problem of determining the schedule that minimizes the overall makespan (i.e., the time when
   all the products have been completed) while satisfying the deadlines. Solve the resulting MILP formulation with Python.</font>

In [1]:
# When using Colab, make sure you run this instruction beforehand
!pip install mip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 8.1 MB/s eta 0:00:00


In [2]:
import mip
import pandas as pd # to handle the data of the problem
from mip import BINARY
import numpy as np
import time

In [3]:
# SET AND PARAMETER DEFINITION

# set of products
n = 6
J = range(n)
# set of machines
m = 3
K = range(m)

# Estimated processing time
p = np.array([[3.,6,4],[4,8,1],[2,4,5],[7,9,6],[8,3,7],[3,4,4]])


# Deadline
d = [38,40,35,35,37,20]

bigM = max(d)

In [4]:
model = 

In [5]:
t = 
y =
eta = 

In [6]:
model.objective = 

# CONSTRAINT
# Eta max


# Deadline


# Disjunction 1


# Disjunction 2


# Sequence


In [7]:
# optimizing
model.optimize()

<OptimizationStatus.OPTIMAL: 0>

In [8]:
model.objective.x

39.0

In [9]:
res_t = np.zeros((n,m))
for j in J:
  for k in K:
      res_t[j,k] = t[j][k].x
print('Variable t')
print(res_t)
print('\n')
print('Variable y')
for k in K:
  print('K:',k)
  res_t = np.zeros((n,n))
  for j in J:
    for j1 in J:
        res_t[j,j1] = y[(j,j1,k)].x
  print(res_t)

Variable t
[[20. 24. 34.]
 [23. 30. 38.]
 [ 0.  2. 14.]
 [ 5. 12. 21.]
 [12. 21. 27.]
 [ 2.  6. 10.]]


Variable y
K: 0
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
K: 1
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
K: 2
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


**2)** <font size="4">Verify that, if you replace the deadline vector $d$ with $d = (32; 34; 33; 28; 32; 18)$, the
problem is infeasible.</font> 

In [10]:
# SET AND PARAMETER DEFINITION

# set of products
n = 6
J = range(n)
# set of machines
m = 3
K = range(m)

# Estimated processing time
p = np.array([[3.,6,4],[4,8,1],[2,4,5],[7,9,6],[8,3,7],[3,4,4]])

# Deadline
d = [32,34,33,28,32,18]

bigM = max(d)

In [11]:
model = 

In [12]:
t = 
y = 
eta = 

In [13]:
model.objective =

# CONSTRAINT
# Eta max


# Deadline


# Disjunction 1


# Disjunction 2


# Sequence


In [14]:
# optimizing
model.optimize()

<OptimizationStatus.INFEASIBLE: 1>

**3)** <font size="4">Consider again the deadline vector d of the previous point 1. For a given product $i$ and machine $k$, it is possible to decrease by one hour the processing time $p_{ik}$ by paying an extra cost. The processing time reduction is available for all the machines but only for products 2,3,4 and. Write a loop in the such that, at each iteration of the loop:

*   a pair $(i, k)$ with available time processing reduction is selected, and $p_{ik}$ is reduced by one,
*   the scheduling problem is solved with the new value $p_{ik}$ (along with the values updated in the previous iteration).

The loop has to be iterated until the scheduling problem becames feasible.</font>

INFEASIBLE
INFEASIBLE
INFEASIBLE
INFEASIBLE
INFEASIBLE
INFEASIBLE
INFEASIBLE
INFEASIBLE
INFEASIBLE
PROBLEM FEASIBLE
eta:
34.0
Iterations:


10

**Homework**

**4)** <font size="4"> How can the mixed integer linear formulation of point 1) be extended to account for the case where each product must be processed on a (possibly) diffeerent sequence of machines?</font>

**5)** <font size="4"> Modify the above model to allow for soft deadlines, so as to determine the schedule minimizing the total tardiness. The tardiness for an product i is defined as the difference between
its completion time and its deadline (0 if the completion time does not exceed the deadline) </font>

In [17]:
# SET AND PARAMETER DEFINITION

# set of products
n = 6
J = range(n)
# set of machines
m = 3
K = range(m)

# Estimated processing time
p = np.array([[3.,6,4],[4,8,1],[2,4,5],[7,9,6],[8,3,7],[3,4,4]])

# Deadline
d = [32,34,33,28,32,18]

bigM = max(d)

In [18]:
model =

In [19]:
t = 
y = 
rho = 

In [20]:
model.objective = 

# CONSTRAINT

# Soft deadline


# Disjunction 1


# Disjunction 2


# Sequence


In [21]:
# optimizing
model.optimize()

<OptimizationStatus.OPTIMAL: 0>

In [22]:
model.objective.x

11.0

In [23]:
print('Variables rho:')
for j in J:
  print(rho[j].x)
print('\n')
res_t = np.zeros((n,m))
for j in J:
  for k in K:
      res_t[j,k] = t[j][k].x
print('Variable t')
print(res_t)
print('\n')
print('Variable y')
for k in K:
  print('K:',k)
  res_t = np.zeros((n,n))
  for j in J:
    for j1 in J:
        res_t[j,j1] = y[(j,j1,k)].x
  print(res_t)

Variables rho:
0.0
5.0
0.0
0.0
6.0
0.0


Variable t
[[12. 21. 27.]
 [23. 30. 38.]
 [ 0.  4. 16.]
 [ 5. 12. 21.]
 [15. 27. 31.]
 [ 2.  8. 12.]]


Variable y
K: 0
[[0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
K: 1
[[0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
K: 2
[[0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
