**A Column Generation Approach for the Airline Crew Pairing Problem**

This laboratory session is about a subproblem of Airline Crew Scheduling, known in the literature
as the Airline Crew Pairing problem. Let us consider a flight leg which is a single takeofflanding phase to be carried out within a predefined time window, for example a flight that has
to take off from Rome airport FCO at 9:00 AM and has to land at Milan airport MPX at 10:15 AM. A pairing is a feasible sequence of flight legs that can be performed by the same crew members, starting and ending at the same airport. Organizing the daily flights into pairings is an important problem for airline companies, and it is generally followed by an assignment phase
of the crew members to each pairing (a problem known as Airline Crew Rostering). The pairings must be created so as to be feasible with respect to different constraints like, for instance, the
compatibility of the flight legs, minimum rest periods and maximum total flight time.

Given a set $I$ of flight legs, a feasible pairing can be represented by an incidence column
vector $A^j \in \mathbb{R}^I$, with component $a_{ij}$ equal to 1 if the flight leg $i \in I$ is included in the paring and 0 otherwise. Given


*   a set $I$ of flight legs,
*   the set $J$ of all feasible pairings described by the column vectors $A^j$ with $j \in J$,

the Airline Crew Pairing problem consists in selecting the minimum number of feasible pairings
that exactly cover all the flight legs. Note that minimizing the number of pairing amounts to
minimizing the number of crews needed to cover all the flight legs.

Given a set of binary variables $x_j$ with $j \in J$ indicating which feasible pairings are selected, the addressed problem can be formulated as the following set partitioning problem

\begin{array}{lll}
  \min & \sum_\limits{j \in J} x_j & & & \text{(1)}\\
  \textrm{s.t.} & Ax = 1 & & &(2)\\
  & x_{j} \in \{0,1\} &  j \in J, &  &(3)\\
\end{array}

where $A \in \mathbb{R}^{I \times J}$
is the incidence matrix of flight legs and pairings, containing all the feasible
pairing columns $A^j$. Since the number $|J|$ of columns grows exponentially with the number
$|I|$ of flight legs, it is impossible for real-world instances to construct the whole matrix $A$. For this reason a classical way to face this problem is the column generation method, in which the columns of $A$ are generated on the fly  only if needed, by exploiting the dual formulation of the
linear relaxation of problem (1)-(3).

In this laboratory session, we consider an instance of the Airline Crew Pairing problem which involves 9 airports and 42 flight legs. Each flight leg $i \in I$ is characterized by an origin airport $o_i$ and a destination airport $d_i$, a starting time $s_i$ and the length $l_i$ of the flight leg expressed
in hours. The feasible pairings must be created so that the starting and the ending airports coincide and so that there is at least 1 hour of rest period between any two consecutive legs.



1.   Propose a column generation strategy to solve the linear relaxation of the Airline Crew
Pairing problem.

**Hint**:  Exploit the structure of the dual formulation of the problem.



1.   The Linear Programming (LP) relaxation of problem (1)-(3) is

\begin{array}{lll}
  \min & \sum_\limits{j \in J} x_j & & & \text{(4)}\\
  \textrm{s.t.} & Ax = 1 & & &(5)\\
  & x_{j} \geq 0 &  j \in J. &  &(6)\\
\end{array}

Note that constraints $x_j \leq 1$, with $j \in J$, can be neglected due to constraints (5) with all non negative coefficients. Consider a restricted version of problem (4)-(6) involving only a number $n_j << |J|$ of columns of A. This amounts to fixing to 0 all the variables associated to the columns not considered in the restricted version. This problem is the so-called LP Restricted Master problem (LPRM). By solving LPRM with the simplex algorithm, we obtain the optimal solution $x^∗ \in \mathbb{R}^{n_j}$ with the associated vector of optimal dual variables $y^∗ \in \mathbb{R}$. The idea is to look for a non basic variable $x_{j^{'}}$ not included in the LPRM with
negative reduced cost, that is, with

$$\bar{c}_{j^{'}}= 1 - \sum_\limits{i \in I}a_{i{j^{'}}}y_i^*$$

In such a case, the current solution $x^*$
can be improved by adding to the LPRM the
column ($a_{1j^{'}}$ $a_{2j^{'}}$ ... $a_{Ij^{'}})^T$
T with its associated variable $x_{j^{'}}$. Otherwise, if no such (non basic) variable exists, $x^∗$ is optimal also for the original (complete) LP relaxation (4)-(6). To search for an improving non basic variable (and its corresponding column), we can solve the following pricing maximization sub-problem:

$$\max_{\alpha \in \mathbb{R}^I} \sum_\limits{i \in I}y_i^* \alpha_i$$

subject to some constraints which guarantee that the vector α represents a feasible pairing.
To this aim let us consider a graph $G =< I, A >$ where each flight leg represents a node
and each direct arc from node $i_1$ to node node $i_2$ represents a “feasible precedence” of flight leg i1 with respect to flight leg $i_2$, in particular:


*   the destination airport of $i_1$ is the origin airport of $i_2$,
*   there is at least 1 hour of rest period between the arrival time of $i_1$ and the departure time of $i_2$.

By indicating as $(s−t)$ a pair of source-target nodes such that $o_s = d_t$ (the starting airport
and the ending airport must coincide), any existing path from $s$ to $t$ in the graph represents a feasible pairing. Therefore the problem of finding a feasible pairing can be reformulated as the problem of finding an $(s − t)$ path in the directed graph.

Let $G =< I, A >$ the feasible precedence graph, where I is the set of flight legs and $A = {(i_1, i_2) \in I \times I : d_{i_1} = o_{i_2} ∧ s_{i_2} \geq s_{i_1} + l_{i_1} + rest}$. Let $z_{i_1i_2}$ with $i_1$, $i_2 \in I$ be a set of binary variables indicating if an arc from $i_1$ to $i_2$ is activated in the path representing the feasible pairing. For a given $(s − t)$ the pricing subproblem can be formulated as the following graph optimization problem




\begin{array}{lll}
  \max & \sum_\limits{i \in I} y_i^* \alpha_i & & & \text{(7)}\\
  \textrm{s.t.} & \sum_\limits{(s,i)\in \delta^+(i)} z_{si} = \alpha_s & & &(8)\\
   & \sum_\limits{(i,t)\in \delta^-(i)} z_{it} = \alpha_t &   &  &(9)\\
    & \sum_\limits{(h,i)\in \delta^+(i)} z_{hi} - \sum_\limits{(i,j)\in \delta^-(i)} z_{ij} = 0 &  \forall i \in I, i \neq s,t &  &(10)\\
  &\sum_\limits{(i,j)\in \delta^+(i)} z_{ij} = \alpha_i &  \forall i \in I, i \neq s,t, &  &(11)\\
  & \alpha_{i} \in \{0,1\} &  \forall i \in I, &  &(12)\\
  & z_{ii^{'}} \in \{0,1\} &  \forall i,i^{'} \in I, &  &(13)\\
\end{array}






Constraints (8) and (9) on a one hand make sure that the variables $\alpha_s$ and $\alpha_t$ are set to 1 if an arc incident to $s$ and, respectively, to $t$ is activated, on the other hand they ensure the uniqueness of the optimal path. Note that, in the feasible precedence graph, an $(s−t)$ path may not exist. In such a case, imposing $\sum_\limits{(s,i)\in \delta^+(i)} z_{si} = 1 $ and $ \sum_\limits{(i,t)\in \delta^-(i)} z_{it} = 1$, like in the standard shortest or longest path formulations, could lead to the infeasibility of the pricing subproblem, while (8) and (9) admit at least the solution with all variables set to zero. Constraints (10) are classical balance constraints for the intermediate nodes of the path, while constraints (11) are used to activate the variables $\alpha_i$ if the optimal path
goes through node $i$. Let $\alpha^*$ denote an optimal solution of the pricing subproblem. If $1 − \sum_\limits{i \in I}y_i^* \alpha_i < 0$ then $\alpha^*$ is the incidence vector of a feasible pairing associated to a variable with negative reduced
cost, so they can be inserted in the LPRM to improve the current solution.
For a given solution $x^∗$ of the LPRM, the pricing subproblem has to be solved for any
possible pair $(s − t)$ until a vector $\alpha^*$ associated to a negative reduced cost is found. If no such $\alpha^*$ exists, the optimality of $x^∗$ for the LP is certified.


2.   Implement in Python a column generation algorithm and solve the linear relaxation of the master problem for the given instance, starting from a given feasible solution.

In [1]:
# When using Colab, make sure you run this instruction beforehand
!pip install mip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 3.9 MB/s eta 0:00:00


In [2]:
import mip
import pandas as pd # to handle the data of the problem
from mip import BINARY
import numpy as np
import math

In [3]:
data = pd.read_csv('data.csv',sep=';')

# MASTER PROBLEM
# DEFINITION OF SETS AND PARAMETERS

#number of flight legs
n_i = 42

n_q = 9

# set of the flight legs
I = range(n_i)
# set of the airports
Q = range(n_q)

# origin airport of the flight
o = data['o'].values

# destination airport of the flight
d = data['d'].values

# starting time of the flight
s = data['s'].values

# length of the flight
l = data['l'].values

#----------------------------------------
# initialize a starting feasible solution
#----------------------------------------
# number of pairings
n_j = int(n_i/2)

# pairings matrix
a = np.zeros((n_i,n_j))

# Valid pairings for the specific instance in data.csv
for i in I:
  a[i,math.floor(i/2)] = 1

# set of all possible edge 
K = [(i,i1) for i in I for i1 in I]

In [4]:
#----------------------------------------
# create the graph of feasible paths
#----------------------------------------
rest = 1
# TO-DO: modify the arc set A by adding an arc (i, i1) if destination of i coincides with the origin 
# and the time window constraints are satisfied
A = {(i,i1) for (i,i1) in K if d[i] == o[i1] and s[i1]>=s[i]+l[i]+rest}


In [5]:
# function to check if the origin/destination has at least 1 outgoing/ingoing arc
def check(A,index,pos):
  if pos >=0 and pos <=1 and isinstance(pos,int):
    found = False
    for t in A:
      if t[pos] == index:
        found = True
    return found
  else:
    return None

In [6]:
found = True

# cycle until new feasible columns is found
while(found):

  # set of pairings
  J = range(n_j)
  # SOLVE MASTER
  # Master problem definition
  master = mip.Model()

  # variables
  x = [master.add_var(lb=0,name = str(j)) for j in J]

  # objective
  master.objective = mip.minimize(mip.xsum(x[j] for j in J))
  
  # constraints
  for i in I:
    master.add_constr(mip.xsum(a[i,j]*x[j] for j in J)==1)

  
  # optimizing
  master.optimize()
  print('Solved Master pairings:')
  print(master.objective.x)
  # coefficients of the obj. of the pricing set to the shadow price of the master
  y_star = [master.constrs[i].pi for i in I]

  found = False

  # try a pair of flight legs source-target such that:
  # 1. the origin of the source is equal to the target destination
  # 2. the origin has at least 1 outgoing arc
  # 3. the destination has at least 1 ingoing arc

  for (src,trg) in K:
  
    if o[src] == d[trg] and check(A,src,0) and check(A,trg,1):

      found = False

      # SOLVE PRICING
      # Pricing problem definition
      pricing = mip.Model()

      # variables
      alpha = [pricing.add_var(var_type=BINARY,name = str(i)) for i in I]
      z = {edge: pricing.add_var(var_type=BINARY,name ='z_'+str(edge[0])+str(edge[1])) for edge in A}
      

      # objective
      pricing.objective = mip.maximize(mip.xsum(alpha[i]*y_star[i] for i in I))

      # constraints
      # balanceSource
      pricing.add_constr(mip.xsum(z[edge] for edge in A if edge[0]==src)==alpha[src])
      # balanceTarget:
      pricing.add_constr(mip.xsum(z[edge] for edge in A if edge[1]==trg)==alpha[trg])
      # balance
      for i in I:
        if i!= src and i!=trg:
          pricing.add_constr(mip.xsum(z[edge] for edge in A if edge[1]==i)-mip.xsum(z[edge] for edge in A if edge[0]==i) == 0)
      # activation
      for i in I:
        if i!= src and i!=trg:
          pricing.add_constr(mip.xsum(z[edge] for edge in A if edge[1]==i)== alpha[i])
      # optimizing
      pricing.optimize()

      reducedCost = 1 - pricing.objective.x

      if reducedCost < 0:
        n_j += 1
        b = np.zeros((n_i,1))
        print("Found new pairing %i - %i \n" % (src, trg))
        for i in I:
          b[i] = pricing.vars[i].x
        a = np.hstack((a,b))
        found = True
        break

Solved Master pairings:
21.0
Found new pairing 0 - 3 

Solved Master pairings:
20.0
Found new pairing 14 - 17 

Solved Master pairings:
19.0
Found new pairing 30 - 29 

Solved Master pairings:
18.0


In [7]:
indices = []

for j in J:
  if x[j].x == 1:
    indices.append(j)
print("Selected %i pairings" % len(indices))
print(indices)
print(a[:,indices])

Selected 18 pairings
[2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


Starting from an initial feasible solution with 21 pairings, the implemented column generation algorithm attains the optimal solution of the LP with 18 pairings. Note that for this
small size instance the pricing subproblem can be solved exactly with mip. However,
since the pricing subproblem consists in finding longest paths in an acyclic graph, ad-hoc
polynomial time algorithms are available.